@startuml
left to right direction
actor User as user

rectangle "Система бронирования ЖД билетов" {
  user --> (Регистрация)
  user --> (Авторизация)
  user --> (Поиск маршрутов)
  user --> (Оплата заказа)
  user --> (Просмотр забронированных билетов)
  (Выбор типа маршрута) .> (Прямые маршруты) : extend
  (Выбор типа маршрута) ..> (Маршруты с пересадками) : extend
  (Поиск маршрутов) .> (Выбор места) : extend
  (Поиск маршрутов) ..> (Выбор типа маршрута) : include
  
  (Выбор места) .> (Просмотр расписания) : extend
  
  user --> (Просмотр личного кабинета)
  (Просмотр личного кабинета) ..> (Редактирование данных) : extend     
  
  (Просмотр забронированных билетов) ..> (Отмена заказа) : extend
  
  (Отмена заказа) .> (Возврат средств) : extend
}
@enduml